import {describe,expect,it} from "vitest";
import {compositionArgs} from "../src/main/composition-ffmpeg";

describe("composition ffmpeg arguments",()=>{
  it("keeps the stream-copy path without a logo",()=>{const args=compositionArgs({videoPaths:["video.mp4"],audioPath:"audio.m4a",tempPath:"out.mp4",width:1280,height:720});expect(args).toContain("copy");expect(args).not.toContain("-filter_complex");});
  it("overlays a logo for a single video",()=>{const args=compositionArgs({videoPaths:["video.mp4"],audioPath:"audio.m4a",logoPath:"logo.png",tempPath:"out.mp4",width:1280,height:720});expect(args.join(" ")).toContain("overlay=W-w-24:H-h-24");expect(args).toContain("logo.png");expect(args).toContain("[logoout0]");});
  it("overlays after concatenating multiple videos",()=>{const args=compositionArgs({videoPaths:["one.mp4","two.mp4"],audioPath:"audio.m4a",logoPath:"logo.png",tempPath:"out.mp4",width:1280,height:720});const filter=args[args.indexOf("-filter_complex")+1]!;expect(filter).toContain("concat=n=2");expect(filter).toContain("[vbase][logo0]overlay");expect(args).toContain("2:a:0");});
  it("builds independent appearance and movement controls",()=>{const args=compositionArgs({videoPaths:["video.mp4"],audioPath:"audio.m4a",logos:[{path:"logo.png",mode:"horizontal",position:"bottom-center",width:180,opacity:.6,speedX:200,speedY:80,hue:45,backgroundColor:"#ff0000",backgroundOpacity:.4,padding:12,staticEffect:"fade-in",fadeDuration:2}],tempPath:"out.mp4",width:1280,height:720});const filter=args[args.indexOf("-filter_complex")+1]!;expect(filter).toContain("hue=h=45");expect(filter).toContain("color=0xff0000@0.4");expect(filter).toContain("colorchannelmixer=aa=0.6");expect(filter).toContain("fade=t=in:st=0:d=2:alpha=1");expect(filter).toContain("t*200");expect(filter).toContain("y='H-h-24'");});
  it("renders trim, clip speed, audio gain and bounded overlay time",()=>{const args=compositionArgs({videoPaths:["video.mp4"],videoEdits:[{path:"video.mp4",trimStart:1,trimEnd:5,speed:2}],audioPath:"audio.m4a",audioVolume:.5,logos:[{path:"logo.png",mode:"static",position:"top-left",width:100,opacity:1,speedX:100,speedY:100,timelineStart:.5,timelineEnd:1.5}],tempPath:"out.mp4",width:1280,height:720});const filter=args[args.indexOf("-filter_complex")+1]!;expect(filter).toContain("trim=start=1:end=5");expect(filter).toContain("setpts=(PTS-STARTPTS)/2");expect(filter).toContain("enable='between(t,0.5,1.5)'");expect(args.join(" ")).toContain("-af volume=0.5");});
  it("exports freely dragged logo coordinates",()=>{const args=compositionArgs({videoPaths:["video.mp4"],audioPath:"audio.m4a",logos:[{path:"logo.png",mode:"static",position:"center",xPercent:37.5,yPercent:62,width:100,opacity:1,speedX:100,speedY:100}],tempPath:"out.mp4",width:1280,height:720});const filter=args[args.indexOf("-filter_complex")+1]!;expect(filter).toContain("overlay=(W-w)*37.5/100:(H-h)*62/100");});
  it("exports a muted audio track as zero volume",()=>{const args=compositionArgs({videoPaths:["video.mp4"],audioPath:"audio.m4a",audioVolume:0,tempPath:"out.mp4",width:1280,height:720});expect(args.join(" ")).toContain("-af volume=0");});
});
