import {describe,expect,it} from "vitest";
import fs from "node:fs/promises";
import path from "node:path";
import {runTool} from "../src/main/tools";
import {AppDatabase} from "../src/main/db";
import {ProductEvidence} from "../src/main/product-evidence";
import {CompositionManager} from "../src/main/composition";

async function makeFixture(root:string){const video=path.join(root,"input.mp4");const audio=path.join(root,"audio.m4a");const logos=["red","green","white"].map(color=>path.join(root,`logo-${color}.png`));expect((await runTool("ffmpeg",["-y","-f","lavfi","-i","color=c=blue:s=320x240:r=30:d=2","-c:v","libx264","-pix_fmt","yuv420p",video])).code).toBe(0);expect((await runTool("ffmpeg",["-y","-f","lavfi","-i","sine=frequency=440:duration=2","-c:a","aac",audio])).code).toBe(0);for(const [color,file] of [["red",logos[0]],["green",logos[1]],["white",logos[2]]] as const)expect((await runTool("ffmpeg",["-y","-f","lavfi","-i",`color=c=${color}:s=48x32:d=1`,"-frames:v","1",file])).code).toBe(0);return{video,audio,logos};}
async function waitFor(db:AppDatabase,id:string,status:string){for(let i=0;i<120;i++){const job=db.getComposition(id);if(job?.status===status)return job;if(job?.status==="failed")throw new Error(`Composition failed: ${JSON.stringify(job.error)}`);await new Promise(resolve=>setTimeout(resolve,100));}throw new Error(`Timed out waiting for ${status}`);}
async function probe(file:string){const result=await runTool("ffprobe",["-v","error","-print_format","json","-show_streams","-show_format",file]);expect(result.code).toBe(0);return JSON.parse(result.stdout) as {streams:Array<{codec_type:string;width?:number;height?:number;nb_frames?:string}>;format:{duration:string}};}

describe("real multi-logo composition",()=>{it("renders three logos and validates output with ffprobe",async()=>{const root=await fs.mkdtemp(path.join(process.env.TEMP??process.cwd(),"svp-logo-real-"));const input=await makeFixture(root);const db=new AppDatabase(path.join(root,"data"));const manager=new CompositionManager(db,new ProductEvidence(db));const job=manager.create({videoPath:input.video,audioPath:input.audio,destinationDir:root,logos:[{path:input.logos[0],position:"top-left",mode:"static",hue:30,backgroundColor:"#ffff00",backgroundOpacity:.4,padding:8,staticEffect:"fade-in",fadeDuration:.4},{path:input.logos[1],position:"center",mode:"bounce",speedX:180,speedY:140},{path:input.logos[2],position:"bottom-right",mode:"static"}],outputName:"logos"});const done=await waitFor(db,job.id,"completed");const output=done.outputPath!;const stat=await fs.stat(output);expect(stat.size).toBeGreaterThan(0);const info=await probe(output);const video=info.streams.find(stream=>stream.codec_type==="video");expect(video).toMatchObject({width:320,height:240});expect(Number(info.format.duration)).toBeGreaterThan(1);expect(Number(video?.nb_frames??0)).toBeGreaterThan(0);const frame=path.join(root,"frame.png");expect((await runTool("ffmpeg",["-y","-ss","0.5","-i",output,"-frames:v","1",frame])).code).toBe(0);expect((await fs.stat(frame)).size).toBeGreaterThan(0);db.close();await fs.rm(root,{recursive:true,force:true})},60000);});
