import {describe,expect,it} from "vitest";
import fs from "node:fs/promises";
import path from "node:path";
import {runTool} from "../src/main/tools";
import {compositionArgs,type LogoOverlay} from "../src/main/composition-ffmpeg";

async function pixels(file:string,time:number){const result=await runTool("ffmpeg",["-v","error","-ss",String(time),"-i",file,"-frames:v","1","-f","rawvideo","-pix_fmt","rgb24","pipe:1"]);expect(result.code).toBe(0);return Buffer.from(result.stdout,"binary");}
function count(rgb:Buffer,kind:"red"|"green"|"white"){let n=0;for(let i=0;i<rgb.length;i+=3){const r=rgb[i]??0,g=rgb[i+1]??0,b=rgb[i+2]??0;if(kind==="red"&&r>150&&g<130&&b<130)n++;if(kind==="green"&&g>120&&r<150&&b<150)n++;if(kind==="white"&&r>170&&g>170&&b>170)n++;}return n;}
describe("logo frame validation",()=>{it("proves static and bounce logos render and bounce",async()=>{const root=await fs.mkdtemp(path.join(process.env.TEMP??process.cwd(),"svp-frame-"));const video=path.join(root,"v.mp4"),audio=path.join(root,"a.m4a"),r=path.join(root,"r.png"),g=path.join(root,"g.png"),out=path.join(root,"out.mp4");expect((await runTool("ffmpeg",["-y","-f","lavfi","-i","color=c=blue:s=320x240:r=30:d=2","-c:v","libx264","-pix_fmt","yuv420p",video])).code).toBe(0);expect((await runTool("ffmpeg",["-y","-f","lavfi","-i","sine=frequency=440:duration=2","-c:a","aac",audio])).code).toBe(0);for(const [c,f] of [["red",r],["green",g]] as const)expect((await runTool("ffmpeg",["-y","-f","lavfi","-i",`color=c=${c}:s=48x32:d=1`,"-frames:v","1",f])).code).toBe(0);const logos:LogoOverlay[]=[{path:r,mode:"static",position:"top-left",width:48,opacity:1,speedX:120,speedY:90},{path:g,mode:"bounce",position:"center",width:48,opacity:1,speedX:180,speedY:140}];const args=compositionArgs({videoPaths:[video],audioPath:audio,logos,tempPath:out,width:320,height:240});expect((await runTool("ffmpeg",args)).code).toBe(0);const a=await pixels(out,0),b=await pixels(out,.8);expect(count(a,"red")).toBeGreaterThan(100);expect(count(a,"green")).toBeGreaterThan(100);expect(count(a,"green")).toBe(count(b,"green"));await fs.rm(root,{recursive:true,force:true});},60000);});
