import {readFile} from "node:fs/promises";
import {describe,expect,it} from "vitest";
describe("tabbed workspace boundaries",()=>{
  it("keeps all primary workspaces in the tab bar",async()=>{const source=await readFile("src/renderer/app-tabs.tsx","utf8");expect(source).toContain('["download","composition","studio","history"]');expect(source).toContain("data-tab={tab}");expect(source).not.toContain('"tasks"|');expect(source).not.toContain('"settings"|')});
  it("keeps download free of settings, tools and Composition",async()=>{const source=await readFile("src/renderer/download-composer.tsx","utf8");expect(source).not.toContain("historyRetentionDays");expect(source).not.toContain("cookiesFromBrowser");expect(source).not.toContain("tool.version");expect(source).not.toContain("CompositionBuilder")});
  it("places privacy, diagnostics and tools only in settings",async()=>{const source=await readFile("src/renderer/settings-panel.tsx","utf8");expect(source).toContain("EvidenceProbe");expect(source).toContain("exportDiagnostics");expect(source).toContain("cookiesFromBrowser");expect(source).toContain("tools.map")});
  it("offers an opt-in-gated multi-input interest action and refreshes gate progress",async()=>{const source=await readFile("src/renderer/evidence-probe.tsx","utf8");expect(source).toContain('disabled={!settings?.collectProductEvidence}');expect(source).toContain("recordMultiInputIntent");expect(source).toContain("setGate(result.gate)")});
  it("shows every predeclared Composition evidence threshold",async()=>{const source=await readFile("src/renderer/evidence-probe.tsx","utf8");for(const signal of ["minimumActiveDays","minimumMultiInputIntents","minimumCompletedExports","maximumBounceRate"])expect(source).toContain(signal);expect(source).toContain('data-passed={gate.passed}')});
  it("provides a bounded draggable multi-track editor",async()=>{const source=await readFile("src/renderer/composition-builder.tsx","utf8"),compact=source.replace(/\s+/g,"");expect(source).toContain("pickVideos");expect(compact).toContain("additionalVideoPaths:additionalVideos");expect(compact).toContain("slice(0,20)");expect(source).toContain("@xzdarcy/react-timeline-editor");expect(source).toContain("buildTimelineRows");for(const track of ["VIDEO","AUDIO","OVERLAY"])expect(source).toContain(track);expect(source).toContain('aria-label="Playhead"');expect(source).toContain('aria-label="Timeline zoom"');expect(source).toContain("editor-inspector");for(const feature of ["splitClip","sourceTime","undo()","redo()","supercut-project-v1","currentTime-currentVideo.offset","onTimeUpdate","moveOverlay","setPointerCapture","onActionResizing","onActionMoving","videoLocked","audioLocked","audioMuted","overlayLocked","createWaveform","waveformPath","logoAnimationDuration","AiCut timebase"])expect(compact).toContain(feature.replace(/\s+/g,""));});
  it("never returns the timeline setTime result as a React effect cleanup",async()=>{const source=await readFile("src/renderer/composition-builder.tsx","utf8"),compact=source.replace(/\s+/g,"");expect(compact).toContain("useEffect(()=>{professionalTimeline.current?.setTime(playhead);},[playhead])");expect(compact).not.toContain("useEffect(()=>professionalTimeline.current?.setTime(playhead)");});
  it("exposes a borderless or color-configurable logo border",async()=>{const source=await readFile("src/renderer/composition-builder.tsx","utf8");for(const feature of ["borderWidth","borderColor",'aria-label="Độ dày viền logo"','aria-label="Màu viền logo"',"Không viền"])expect(source).toContain(feature);});
  it("keeps logo edits stable and fullscreen inside the composed preview",async()=>{const source=await readFile("src/renderer/composition-builder.tsx","utf8");expect(source).toContain("logoEditActive");expect(source).toContain("beginLogoEdit");expect(source).toContain("togglePreviewFullscreen");expect(source).toContain("canvas.requestFullscreen()");expect(source).toContain('aria-label="Phóng to preview"');expect(source).not.toContain("controls/><div className=\"preview-overlays\"");const styles=await readFile("src/renderer/styles.css","utf8");expect(styles).toContain(".preview-canvas:fullscreen");});
  it("allows exporting a video and logo without a separate audio track",async()=>{const source=await readFile("src/renderer/composition-builder.tsx","utf8"),compact=source.replace(/\s+/g,"");expect(compact).toContain("audioPath:audio?.path");expect(compact).toContain('disabled={!videos.length}');expect(compact).not.toContain('disabled={!videos.length||!audio}');});
  it("supports roving keyboard navigation across workspace tabs",async()=>{const source=await readFile("src/renderer/app-tabs.tsx","utf8");for(const feature of ["ArrowLeft","ArrowRight","Home","End","tabIndex={active===tab?0:-1}","requestAnimationFrame"])expect(source).toContain(feature);});
  it("ships a deterministic local UI audit gate",async()=>{const script=await readFile("scripts/ui-refactor.mjs","utf8");for(const feature of ["SVP_UI_AUDIT","smallTargets","horizontal overflow","report.html","score.json"])expect(script).toContain(feature);const styles=await readFile("src/renderer/styles.css","utf8");expect(styles).toContain("prefers-reduced-motion");expect(styles).toContain("--focus-ring");});
  it("preserves a clear visual hierarchy across editor panels",async()=>{const styles=await readFile("src/renderer/styles.css","utf8");for(const feature of ["--editor-panel",".media-bin h3::before",".preview-canvas",".professional-track-labels",".timeline-editor-action:hover","::-webkit-scrollbar-thumb"])expect(styles).toContain(feature);});
  it("audits the four workspaces plus global task and settings surfaces",async()=>{const config=JSON.parse(await readFile(".ui-refactor/config.json","utf8")) as {tabs:string[];surfaces:string[]};expect(config.tabs).toEqual(["download","composition","studio","history"]);expect(config.surfaces).toEqual(["tasks","settings"]);const app=await readFile("src/renderer/App.tsx","utf8");for(const feature of ["task-drawer","settings-modal",'aria-modal="true"','event.key==="Escape"',"inert={tasksOpen||settingsOpen||undefined}","JobQueue scope=\"active\"","SettingsPanel"])expect(app).toContain(feature);const styles=await readFile("src/renderer/styles.css","utf8");for(const feature of ["width:min(1360px",".app-tabs button::after",".settings-card::before",".surface-backdrop",".task-drawer",".settings-modal"])expect(styles).toContain(feature);const main=await readFile("src/main/index.ts","utf8");expect(main).toContain("SVP_SCREENSHOT_SURFACE");expect(main).toContain("element.closest('label')");});
});
