import {spawn,type ChildProcess} from "node:child_process";
import http from "node:http";
export type BackendLifecycleOptions={url:string;command?:string;args?:string[];cwd?:string;timeoutMs?:number;pollMs?:number;spawnProcess?:(command:string,args:string[],options:object)=>ChildProcess;healthCheck?:()=>Promise<boolean>;logger?:(level:"info"|"error",message:string)=>void};
export class BackendLifecycle{private child?:ChildProcess;private owned=false;private stopping=false;private starting?:Promise<{ready:boolean;owned:boolean}>;private opts:BackendLifecycleOptions;constructor(opts:BackendLifecycleOptions){this.opts={timeoutMs:10000,pollMs:150,...opts};}
  private probe(){if(this.opts.healthCheck)return this.opts.healthCheck();return new Promise<boolean>(resolve=>{const req=http.get(`${this.opts.url}/health`,res=>{res.resume();resolve(res.statusCode===200);});req.on("error",()=>resolve(false));req.setTimeout(800,()=>{req.destroy();resolve(false);});});}
  start(){if(!this.starting)this.starting=this.startOnce().catch(error=>{this.starting=undefined;throw error;});return this.starting;}
  private async startOnce(){if(await this.probe())return {ready:true,owned:false};const command=this.opts.command??"python";const args=this.opts.args??["-m","uvicorn","newsvid.api:create_app","--factory","--host","127.0.0.1","--port","8787"];const spawnProcess=this.opts.spawnProcess??((c,a,o)=>spawn(c,a,{...o,windowsHide:true}));this.stopping=false;this.child=spawnProcess(command,args,{cwd:this.opts.cwd,stdio:["ignore","pipe","pipe"]});this.owned=true;let output="";const log=this.opts.logger??((level,message)=>level==="error"?console.error(message):console.info(message));this.child.stdout?.on("data",d=>{const message=String(d);output+=message;log("info",`[newsvid] ${message.trim()}`);});this.child.stderr?.on("data",d=>{const message=String(d);output+=message;log("error",`[newsvid] ${message.trim()}`);});this.child.on("exit",code=>{if(this.owned&&!this.stopping)log("error",`NewsVid backend exited unexpectedly with code ${code}`);});const deadline=Date.now()+(this.opts.timeoutMs??10000);while(Date.now()<deadline){if(this.child.exitCode!==null)throw new Error(`Backend exited before readiness: ${output}`);if(await this.probe())return {ready:true,owned:true};await new Promise(r=>setTimeout(r,this.opts.pollMs));}await this.stop();throw new Error(`Backend readiness timeout: ${output}`);}
  async stop(){if(!this.owned||!this.child)return;const child=this.child;this.child=undefined;this.stopping=true;this.owned=false;if(child.exitCode===null)child.kill();}
  get ownedByElectron(){return this.owned;}
}
