import fs from "node:fs/promises";import path from "node:path";import crypto from "node:crypto";import {spawnSync} from "node:child_process";
const dir=path.resolve("vendor/tools");await fs.mkdir(dir,{recursive:true});
const yt={version:"2026.06.09",url:"https://github.com/yt-dlp/yt-dlp/releases/download/2026.06.09/yt-dlp.exe",sha256:"3a48cb955d55c8821b60ccbdbbc6f61bc958f2f3d3b7ad5eaf3d83a543293a27"};
const deno={version:"2.9.5",url:"https://github.com/denoland/deno/releases/download/v2.9.5/deno-x86_64-pc-windows-msvc.zip",archiveSha256:"171efab55ac6b9881fd53ee4c20f8bf3bb1340ffc618483746909014db12216a",sha256:"98f8c2a2d470e4ccb04c935c86ff8050817d877762aec5eaeeb9e409ccb3b9fd"};
async function hash(file){return crypto.createHash("sha256").update(await fs.readFile(file)).digest("hex")}
async function ensureYtDlp(){const target=path.join(dir,"yt-dlp.exe");try{if(await hash(target)===yt.sha256)return}catch{}const response=await fetch(yt.url,{redirect:"follow"});if(!response.ok)throw new Error(`yt-dlp download failed: ${response.status}`);await fs.writeFile(target,new Uint8Array(await response.arrayBuffer()));const actual=await hash(target);if(actual!==yt.sha256){await fs.rm(target,{force:true});throw new Error(`yt-dlp checksum mismatch: ${actual}`)}}
async function ensureDeno(){const target=path.join(dir,"deno.exe");try{if(await hash(target)===deno.sha256)return}catch{}const archive=path.join(dir,"deno.zip");const response=await fetch(deno.url,{redirect:"follow"});if(!response.ok)throw new Error(`Deno download failed: ${response.status}`);await fs.writeFile(archive,new Uint8Array(await response.arrayBuffer()));const archiveHash=await hash(archive);if(archiveHash!==deno.archiveSha256){await fs.rm(archive,{force:true});throw new Error(`Deno archive checksum mismatch: ${archiveHash}`)}const extracted=spawnSync("tar.exe",["-xf",archive,"-C",dir],{encoding:"utf8",windowsHide:true});await fs.rm(archive,{force:true});if(extracted.status!==0)throw new Error(`Deno extraction failed: ${extracted.stderr}`);const actual=await hash(target);if(actual!==deno.sha256){await fs.rm(target,{force:true});throw new Error(`Deno checksum mismatch: ${actual}`)}}
async function stagePathTool(name){const result=spawnSync("where.exe",[`${name}.exe`],{encoding:"utf8",windowsHide:true});let source=result.stdout?.split(/\r?\n/).map(v=>v.trim()).find(Boolean);if(!source)throw new Error(`${name}.exe is required to build the self-contained Windows installer`);try{const shim=await fs.readFile(`${source}.shim`,"utf8");const target=shim.match(/^path\s*=\s*"([^"]+)"/m)?.[1];if(target)source=target;}catch{}const probe=spawnSync(source,["-version"],{encoding:"utf8",windowsHide:true});if(probe.status!==0)throw new Error(`${name}.exe staging source is not executable: ${source}`);await fs.copyFile(source,path.join(dir,`${name}.exe`))}
await ensureYtDlp();await ensureDeno();await stagePathTool("ffmpeg");await stagePathTool("ffprobe");
await fs.writeFile(path.join(dir,"manifest.json"),JSON.stringify({generatedAt:new Date().toISOString(),tools:{ytDlp:yt,deno,ffmpeg:"staged-from-verified-build-host",ffprobe:"staged-from-verified-build-host"}},null,2));
console.log(`Prepared runtime tools in ${dir}`);
