import type {AppSettings,CompositionJob,CompositionSpec,DownloadJob,MediaResource} from "../shared/contracts";
import type { IpcChannel } from "../shared/ipc";
async function invoke<T>(channel:IpcChannel,input:unknown={}):Promise<T>{ const result=await window.superVideo.invoke(channel,input); if(!result.ok)throw new Error(result.error.message); return result.data as T; }
function isDownloadJob(value:unknown):value is DownloadJob{return Boolean(value&&typeof value==="object"&&"id" in value&&typeof value.id==="string"&&"status" in value&&typeof value.status==="string"&&"createdAt" in value&&typeof value.createdAt==="string");}
function isCompositionJob(value:unknown):value is CompositionJob{return Boolean(value&&typeof value==="object"&&"id" in value&&typeof value.id==="string"&&"spec" in value&&"status" in value);}
export type EvidenceGate={passed:boolean;activeDays:number;bounceRate:number;thresholds:{minimumActiveDays:number;minimumMultiInputIntents:number;minimumCompletedExports:number;maximumBounceRate:number};summary:Record<string,{count:number;activeDays:number}>};
export const pickCompositionLogo=()=>invoke<string|null>("dialog:composition-logo",{});
export const inspectCompositionFile=(path:string)=>invoke<{duration:number;width:number;height:number;kinds:string[]}>("compositions:inspect-file",{path});
export const createWaveform=(path:string)=>invoke<{path:string}>("compositions:waveform",{path});
export const api={ app:{info:()=>invoke<{version:string;platform:string;updatesConfigured:boolean}>("app:get-info"),logAction:(action:string,details:Record<string,string|number|boolean|null>={})=>invoke<{logged:boolean}>("app:log-action",{action,details}),windowControl:(action:"minimize"|"toggle-maximize"|"close")=>invoke<{maximized:boolean}>("window:control",{action}),toolStatus:()=>invoke<Array<{name:string;available:boolean;version:string|null}>>("tools:status"),exportDiagnostics:(fileName?:string)=>invoke<string|null>("diagnostics:export",{fileName}),checkUpdates:()=>invoke<{state:string;message?:string;version?:string}>("updates:check"),showItem:(path:string)=>invoke<{shown:boolean}>("shell:show-item",{path})},media:{inspect:(sourceUrl:string)=>invoke<MediaResource>("media:inspect",{sourceUrl})},evidence:{gate:()=>invoke<EvidenceGate>("evidence:gate"),recordMultiInputIntent:()=>invoke<{recorded:boolean;gate:EvidenceGate}>("evidence:multi-input-intent"),export:()=>invoke<string|null>("evidence:export")},compositions:{list:()=>invoke<CompositionJob[]>("compositions:list"),pick:(kind:"video"|"audio")=>invoke<string|null>("dialog:composition-input",{kind}),pickVideos:()=>invoke<string[]>("dialog:composition-videos"),create:(spec:CompositionSpec)=>invoke<CompositionJob>("compositions:create",spec),command:(action:"cancel"|"retry",compositionId:string)=>invoke<CompositionJob>(`compositions:${action}`,{compositionId}),remove:(compositionId:string)=>invoke<{removed:boolean}>("compositions:remove",{compositionId}),subscribe:(callback:(job:CompositionJob)=>void)=>window.superVideo.onCompositionsChanged(raw=>{if(isCompositionJob(raw))callback(raw);})},jobs:{list:()=>invoke<DownloadJob[]>("jobs:list",{limit:200}),subscribe:(callback:(job:DownloadJob)=>void)=>window.superVideo.onJobsChanged(raw=>{if(isDownloadJob(raw))callback(raw);}),create:(sourceUrl:string,destinationDir?:string,resource?:MediaResource,selectedVariantId?:string)=>invoke<DownloadJob>("jobs:create",{sourceUrl,destinationDir,priority:50,resource,selectedVariantId}),command:(channel:"jobs:pause"|"jobs:resume"|"jobs:cancel"|"jobs:retry",jobId:string)=>invoke<DownloadJob>(channel,{jobId}),remove:(jobId:string)=>invoke<{removed:boolean}>("jobs:remove",{jobId}),clearTerminal:()=>invoke<{removed:number}>("jobs:clear-terminal",{})},settings:{get:()=>invoke<AppSettings>("settings:get"),update:(value:Partial<AppSettings>)=>invoke<AppSettings>("settings:update",value),pickDir:()=>invoke<string|null>("dialog:download-dir")}};
