import { useEffect, useRef, useState } from "react";
import type { DownloadJob, MediaResource } from "../shared/contracts";
import { api } from "./api";
import { useAppStore } from "./store";
import {WindowBar} from "./window-bar";
import {AppHeader} from "./app-header";
import {DownloadComposer} from "./download-composer";
import {JobQueue} from "./job-queue";
import {hydratedUiState,recentUrlsWith} from "./ui-state";
import {EvidenceProbe} from "./evidence-probe";
import {CompositionBuilder} from "./composition-builder";

export function App(){
  const {settings,load,add,saveSettings}=useAppStore();
  const [url,setUrl]=useState("");const [resource,setResource]=useState<MediaResource>();const [selected,setSelected]=useState("");const [inspecting,setInspecting]=useState(false);const [inspectError,setInspectError]=useState("");const [batch,setBatch]=useState(false);const [tools,setTools]=useState<Array<{name:string;available:boolean;version:string|null}>>([]);const [filter,setFilter]=useState<"all"|DownloadJob["status"]>("all");const [query,setQuery]=useState("");const [version,setVersion]=useState("");const [updatesConfigured,setUpdatesConfigured]=useState(false);const [debugFileName,setDebugFileName]=useState("");const hydrated=useRef(false);
  useEffect(()=>{void load();const unsubscribe=api.jobs.subscribe(job=>useAppStore.getState().upsertJob(job));void api.app.toolStatus().then(setTools);void api.app.info().then(info=>{setVersion(info.version);setUpdatesConfigured(info.updatesConfigured);});void api.app.logAction("app.renderer.ready");return unsubscribe;},[load]);
  useEffect(()=>{if(!settings||hydrated.current)return;hydrated.current=true;const state=hydratedUiState(settings);setUrl(state.url);setBatch(state.batch);setQuery(state.query);setFilter(state.filter);setDebugFileName(state.debugFileName);},[settings]);
  useEffect(()=>{if(!hydrated.current||!settings?.rememberUiState)return;const timer=setTimeout(()=>void saveSettings({lastSourceInput:url,downloadMode:batch?"batch":"single",queueSearch:query,queueStatusFilter:filter,diagnosticsFileName:debugFileName}),450);return()=>clearTimeout(timer);},[url,batch,query,filter,debugFileName,settings?.rememberUiState,saveSettings]);
  async function rememberUrl(source:string){await saveSettings({recentUrls:recentUrlsWith(source,settings?.recentUrls??[])});}
  async function inspect(){if(!url.trim())return;setInspecting(true);setInspectError("");void api.app.logAction("media.inspect.start");try{const source=url.trim();const parsed=new URL(source);if(["http:","https:"].includes(parsed.protocol))await rememberUrl(source);const found=await api.media.inspect(source);setResource(found);setSelected(found.variants[0]?.id??"");void api.app.logAction("media.inspect.success",{extractor:found.extractor,variants:found.variants.length});}catch(reason){setResource(undefined);setInspectError(reason instanceof Error?reason.message:String(reason));void api.app.logAction("media.inspect.failure");}finally{setInspecting(false);}}
  async function submit(event:React.FormEvent){event.preventDefault();if(batch){const urls=[...new Set(url.split(/\r?\n/).map(value=>value.trim()).filter(Boolean))];setInspecting(true);void api.app.logAction("batch.download.start",{count:urls.length});const failures:string[]=[];const accepted:string[]=[];for(const source of urls){try{const found=await api.media.inspect(source);await add(source,found,found.variants[0]?.id);accepted.push(source);}catch(reason){failures.push(`${source}: ${reason instanceof Error?reason.message:String(reason)}`);}}if(accepted.length)await saveSettings({recentUrls:[...accepted.reverse(),...(settings?.recentUrls??[]).filter(item=>!accepted.includes(item))].slice(0,30)});setInspectError(failures.join("\n"));setInspecting(false);void api.app.logAction("batch.download.finish",{count:urls.length,failures:failures.length});if(!failures.length)setUrl("");return;}if(!resource){await inspect();return;}await add(url.trim(),resource,selected||undefined);setUrl("");setResource(undefined);setSelected("");}
  return <><WindowBar version={version}/><main><AppHeader debugFileName={debugFileName} setDebugFileName={setDebugFileName} updatesConfigured={updatesConfigured}/><DownloadComposer url={url} setUrl={setUrl} resource={resource} setResource={setResource} selected={selected} setSelected={setSelected} inspecting={inspecting} inspectError={inspectError} setInspectError={setInspectError} batch={batch} setBatch={setBatch} tools={tools} inspect={inspect} submit={submit}/><CompositionBuilder/><EvidenceProbe/><JobQueue filter={filter} setFilter={setFilter} query={query} setQuery={setQuery}/></main></>;
}
