import {useEffect,useMemo,useRef,useState} from "react";
import {z} from "zod";
import {CompositionLogo} from "../shared/contracts";
import {api,createWaveform,inspectCompositionFile,pickCompositionLogo} from "./api";
import {t} from "./i18n";
import {useAppStore} from "./store";

type Logo=z.infer<typeof CompositionLogo>&{id:string};
type Clip={id:string;path:string;duration:number;width:number;height:number;trimStart:number;trimEnd:number;speed:number;waveformPath?:string};
type Selection={kind:"video"|"audio"|"logo";id:string}|null;
type TrackState={videoLocked:boolean;audioLocked:boolean;audioMuted:boolean;overlayLocked:boolean};
type ProjectSnapshot={videos:Clip[];audio:Clip|null;audioVolume:number;logos:Logo[];name:string;tracks:TrackState};
const positions:Logo["position"][]=["top-left","top-center","top-right","middle-left","center","middle-right","bottom-left","bottom-center","bottom-right"];
const uid=()=>crypto.randomUUID();
const basename=(path:string)=>path.split(/[\\/]/).pop()||path;
const fileUrl=(path:string)=>encodeURI(`file:///${path.replaceAll("\\","/")}`);
const clock=(seconds:number)=>`${Math.floor(seconds/60).toString().padStart(2,"0")}:${Math.floor(seconds%60).toString().padStart(2,"0")}`;
const defaultLogo=(path:string):Logo=>({id:uid(),path,mode:"static",position:"bottom-right",width:220,opacity:1,speedX:120,speedY:90,hue:0,backgroundColor:"#000000",backgroundOpacity:0,padding:0,staticEffect:"none",fadeDuration:1,timelineStart:0});
const clipDuration=(clip:Clip)=>Math.max(.01,(clip.trimEnd-clip.trimStart)/clip.speed);

export function CompositionBuilder(){
  const settings=useAppStore(state=>state.settings);
  const [videos,setVideos]=useState<Clip[]>([]);
  const [audio,setAudio]=useState<Clip|null>(null);
  const [audioVolume,setAudioVolume]=useState(1);
  const [tracks,setTracks]=useState<TrackState>({videoLocked:false,audioLocked:false,audioMuted:false,overlayLocked:false});
  const [logos,setLogos]=useState<Logo[]>([]);
  const [selection,setSelection]=useState<Selection>(null);
  const [playhead,setPlayhead]=useState(0);
  const [zoom,setZoom]=useState(1);
  const [snapping,setSnapping]=useState(true);
  const [name,setName]=useState("");
  const [error,setError]=useState("");
  const [message,setMessage]=useState("");
  const [dragged,setDragged]=useState<string|null>(null);
  const [dragOverlay,setDragOverlay]=useState<string|null>(null);
  const [history,setHistory]=useState<ProjectSnapshot[]>([]);
  const [future,setFuture]=useState<ProjectSnapshot[]>([]);
  const preview=useRef<HTMLVideoElement>(null);
  const duration=useMemo(()=>videos.reduce((sum,item)=>sum+clipDuration(item),0),[videos]);
  const selectedVideo=selection?.kind==="video"?videos.find(item=>item.id===selection.id):undefined;
  const selectedLogo=selection?.kind==="logo"?logos.find(item=>item.id===selection.id):undefined;
  const currentVideo=useMemo(()=>{let cursor=0;for(const clip of videos){const editedDuration=clipDuration(clip);if(playhead<=cursor+editedDuration)return{clip,start:cursor,offset:clip.trimStart+Math.max(0,playhead-cursor)*clip.speed};cursor+=editedDuration;}const clip=videos[videos.length-1];return clip?{clip,start:Math.max(0,duration-clipDuration(clip)),offset:clip.trimEnd}:null;},[videos,playhead,duration]);
  useEffect(()=>{const element=preview.current;if(!element||!currentVideo)return;if(Math.abs(element.currentTime-currentVideo.offset)>.12)element.currentTime=Math.min(currentVideo.offset,currentVideo.clip.trimEnd);},[playhead,currentVideo?.clip.id,currentVideo?.offset,currentVideo?.clip.trimEnd]);
  const snapshot=():ProjectSnapshot=>({videos,audio,audioVolume,logos,name,tracks});
  function restore(project:ProjectSnapshot){setVideos(project.videos);setAudio(project.audio);setAudioVolume(project.audioVolume);setLogos(project.logos);setName(project.name);setTracks(project.tracks??{videoLocked:false,audioLocked:false,audioMuted:false,overlayLocked:false});setSelection(null);setPlayhead(0);}
  function checkpoint(){setHistory(current=>[...current.slice(-39),snapshot()]);setFuture([]);}
  function undo(){const previous=history.at(-1);if(!previous)return;setFuture(current=>[snapshot(),...current].slice(0,40));setHistory(current=>current.slice(0,-1));restore(previous);}
  function redo(){const next=future[0];if(!next)return;setHistory(current=>[...current,snapshot()].slice(-40));setFuture(current=>current.slice(1));restore(next);}
  function saveProject(){localStorage.setItem("supercut-project-v1",JSON.stringify(snapshot()));setMessage("Đã lưu project trên thiết bị này.");}
  function loadProject(){try{const raw=localStorage.getItem("supercut-project-v1");if(!raw)throw new Error("Chưa có project đã lưu");checkpoint();restore(JSON.parse(raw) as ProjectSnapshot);setMessage("Đã khôi phục project.");}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}}
  useEffect(()=>{const keyboard=(event:KeyboardEvent)=>{if(!(event.ctrlKey||event.metaKey))return;if(event.key.toLowerCase()==="z"){event.preventDefault();event.shiftKey?redo():undo();}if(event.key.toLowerCase()==="y"){event.preventDefault();redo();}};window.addEventListener("keydown",keyboard);return()=>window.removeEventListener("keydown",keyboard);});
  async function metadata(path:string){const info=await inspectCompositionFile(path);const mediaDuration=info.duration||1;return{id:uid(),path,duration:mediaDuration,width:info.width,height:info.height,trimStart:0,trimEnd:mediaDuration,speed:1};}
  async function addVideos(){try{const paths=await api.compositions.pickVideos();const clips=await Promise.all(paths.map(metadata));if(clips.length)checkpoint();setVideos(current=>[...current,...clips].slice(0,20));if(clips[0])setSelection({kind:"video",id:clips[0].id});}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}}
  async function chooseAudio(){const path=await api.compositions.pick("audio");if(!path)return;try{const clip=await metadata(path);const waveform=await createWaveform(path).catch(()=>null);const ready={...clip,waveformPath:waveform?.path};checkpoint();setAudio(ready);setSelection({kind:"audio",id:ready.id});}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}}
  async function addLogo(){if(logos.length>=8)return;const path=await pickCompositionLogo();if(!path)return;const logo=defaultLogo(path);checkpoint();setLogos(current=>[...current,logo]);setSelection({kind:"logo",id:logo.id});}
  function updateLogo(patch:Partial<Logo>){if(selection?.kind!=="logo"||tracks.overlayLocked)return;checkpoint();setLogos(current=>current.map(item=>item.id===selection.id?{...item,...patch}:item));}
  function updateVideo(patch:Partial<Clip>){if(selection?.kind!=="video"||tracks.videoLocked)return;checkpoint();setVideos(current=>current.map(item=>item.id===selection.id?{...item,...patch}:item));}
  function dropVideo(target:string){if(tracks.videoLocked||!dragged||dragged===target)return;checkpoint();setVideos(current=>{const from=current.findIndex(item=>item.id===dragged),to=current.findIndex(item=>item.id===target);if(from<0||to<0)return current;const next=[...current];const [clip]=next.splice(from,1);next.splice(to,0,clip!);return next;});setDragged(null);}
  function removeSelection(){if(!selection||(selection.kind==="video"&&tracks.videoLocked)||(selection.kind==="audio"&&tracks.audioLocked)||(selection.kind==="logo"&&tracks.overlayLocked))return;checkpoint();if(selection.kind==="video")setVideos(current=>current.filter(item=>item.id!==selection.id));if(selection.kind==="logo")setLogos(current=>current.filter(item=>item.id!==selection.id));if(selection.kind==="audio")setAudio(null);setSelection(null);}
  function splitClip(){if(tracks.videoLocked||selection?.kind!=="video"||videos.length>=20)return;const index=videos.findIndex(item=>item.id===selection.id);if(index<0)return;const clip=videos[index]!;const start=videos.slice(0,index).reduce((sum,item)=>sum+clipDuration(item),0);const relative=playhead-start;if(relative<=.05||relative>=clipDuration(clip)-.05){setError("Đặt playhead vào bên trong clip để tách.");return;}const sourceTime=clip.trimStart+relative*clip.speed;const right={...clip,id:uid(),trimStart:sourceTime};checkpoint();setVideos(current=>[...current.slice(0,index),{...clip,trimEnd:sourceTime},right,...current.slice(index+1)]);setSelection({kind:"video",id:right.id});}
  function moveOverlay(event:React.PointerEvent<HTMLImageElement>,id:string){if(tracks.overlayLocked||dragOverlay!==id)return;const rect=event.currentTarget.parentElement?.parentElement?.getBoundingClientRect();if(!rect)return;const x=Math.max(0,Math.min(100,(event.clientX-rect.left)/rect.width*100));const y=Math.max(0,Math.min(100,(event.clientY-rect.top)/rect.height*100));setLogos(current=>current.map(item=>item.id===id?{...item,xPercent:x,yPercent:y}:item));}
  function startTrim(event:React.PointerEvent<HTMLSpanElement>,clip:Clip,edge:"start"|"end"){
    if(tracks.videoLocked)return;event.preventDefault();event.stopPropagation();checkpoint();setSelection({kind:"video",id:clip.id});
    const startX=event.clientX,initialStart=clip.trimStart,initialEnd=clip.trimEnd,pixelsPerSecond=Math.max(1,(timelineWidth-92)/Math.max(duration,.01));
    const move=(pointer:PointerEvent)=>{const delta=(pointer.clientX-startX)/pixelsPerSecond*clip.speed;let value=edge==="start"?initialStart+delta:initialEnd+delta;if(snapping)value=Math.round(value*30)/30;const nextStart=edge==="start"?Math.max(0,Math.min(value,initialEnd-1/30)):initialStart;const nextEnd=edge==="end"?Math.min(clip.duration,Math.max(value,initialStart+1/30)):initialEnd;setVideos(current=>current.map(item=>item.id===clip.id?{...item,trimStart:nextStart,trimEnd:nextEnd}:item));};
    const end=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",end);};window.addEventListener("pointermove",move);window.addEventListener("pointerup",end,{once:true});
  }
  function seek(value:number){let target=Math.max(0,Math.min(value,duration));if(snapping){const boundaries=[0,duration];let cursor=0;for(const clip of videos){cursor+=clipDuration(clip);boundaries.push(cursor);}const nearest=boundaries.reduce((best,item)=>Math.abs(item-target)<Math.abs(best-target)?item:best,boundaries[0]??0);target=Math.abs(nearest-target)<=.12?nearest:Math.round(target*30)/30;}setPlayhead(target);}
  function stepFrame(direction:-1|1){seek(playhead+direction/30);}
  async function create(){if(!settings||!videos.length||!audio)return;setError("");setMessage("");const video=videos[0]!.path;const additionalVideos=videos.slice(1).map(item=>item.path);try{await api.compositions.create({videoPath:video,additionalVideoPaths:additionalVideos,videoEdits:videos.map(item=>({path:item.path,trimStart:item.trimStart,trimEnd:item.trimEnd,speed:item.speed})),audioPath:audio.path,audioVolume:tracks.audioMuted?0:audioVolume,logos:logos.map(({id,...logo})=>({...logo,timelineEnd:logo.timelineEnd??duration})),destinationDir:settings.downloadDir,outputName:name.trim()||undefined});setMessage(t("composition_queued"));}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}}
  const timelineWidth=Math.max(760,duration*42*zoom);
  return <section className="video-editor">
    <header className="editor-topbar"><div><strong>SuperCut Studio</strong><span>{videos.length?name||"Dự án chưa đặt tên":"Dự án mới"}</span></div><div className="editor-project-actions"><button onClick={undo} disabled={!history.length} title="Ctrl+Z">↶</button><button onClick={redo} disabled={!future.length} title="Ctrl+Y">↷</button><button onClick={()=>stepFrame(-1)} title="Lùi 1 frame">◀│</button><button onClick={()=>stepFrame(1)} title="Tiến 1 frame">│▶</button><button className={snapping?"active":""} onClick={()=>setSnapping(value=>!value)} title="Bật/tắt snapping">🧲</button><button onClick={splitClip} disabled={selection?.kind!=="video"||videos.length>=20}>✂ Tách</button><button onClick={saveProject}>Lưu</button><button onClick={loadProject}>Mở</button><div className="editor-project-name"><input value={name} maxLength={120} onChange={event=>setName(event.target.value)} placeholder="Tên video xuất"/><button className="primary-download" disabled={!videos.length||!audio} onClick={()=>void create()}>Xuất video</button></div></div></header>
    <div className="editor-workspace">
      <aside className="media-bin"><h3>Thư viện</h3><button onClick={()=>void addVideos()}>＋ Video</button><button onClick={()=>void chooseAudio()}>♫ Âm thanh</button><button onClick={()=>void addLogo()}>◇ Logo</button><div className="media-assets">{videos.map(item=><button className={selection?.id===item.id?"selected":""} key={item.id} onClick={()=>setSelection({kind:"video",id:item.id})}><i>▶</i><span>{basename(item.path)}<small>{clock(item.duration)} · {item.width}×{item.height}</small></span></button>)}{audio&&<button className={selection?.id===audio.id?"selected":""} onClick={()=>setSelection({kind:"audio",id:audio.id})}><i>♫</i><span>{basename(audio.path)}<small>{clock(audio.duration)}</small></span></button>}{logos.map(item=><button className={selection?.id===item.id?"selected":""} key={item.id} onClick={()=>setSelection({kind:"logo",id:item.id})}><i>◇</i><span>{basename(item.path)}<small>Logo overlay</small></span></button>)}</div></aside>
      <main className="editor-stage"><div className="preview-canvas">{currentVideo?<><video ref={preview} key={currentVideo.clip.id} src={fileUrl(currentVideo.clip.path)} onLoadedMetadata={event=>{event.currentTarget.currentTime=currentVideo.offset;}} onTimeUpdate={event=>{if(!currentVideo)return;const source=Math.min(event.currentTarget.currentTime,currentVideo.clip.trimEnd);setPlayhead(Math.min(duration,currentVideo.start+(source-currentVideo.clip.trimStart)/currentVideo.clip.speed));}} controls/><div className="preview-overlays">{logos.filter(logo=>playhead>=logo.timelineStart&&playhead<=(logo.timelineEnd??duration)).map(logo=><img key={logo.id} src={fileUrl(logo.path)} className={selection?.id===logo.id?"selected":""} style={logo.xPercent===undefined?{width:`${Math.min(52,logo.width/8)}%`,opacity:logo.opacity,filter:`hue-rotate(${logo.hue}deg)`,padding:logo.padding/5,backgroundColor:`${logo.backgroundColor}${Math.round(logo.backgroundOpacity*255).toString(16).padStart(2,"0")}`}:{left:`${logo.xPercent}%`,top:`${logo.yPercent}%`,transform:"translate(-50%,-50%)",width:`${Math.min(52,logo.width/8)}%`,opacity:logo.opacity,filter:`hue-rotate(${logo.hue}deg)`,padding:logo.padding/5,backgroundColor:`${logo.backgroundColor}${Math.round(logo.backgroundOpacity*255).toString(16).padStart(2,"0")}`}} data-position={logo.xPercent===undefined?logo.position:"custom"} data-mode={logo.mode} onPointerDown={event=>{event.preventDefault();checkpoint();setSelection({kind:"logo",id:logo.id});setDragOverlay(logo.id);event.currentTarget.setPointerCapture(event.pointerId);}} onPointerMove={event=>moveOverlay(event,logo.id)} onPointerUp={()=>setDragOverlay(null)}/>)}</div></>:<div className="preview-empty"><b>▶</b><span>Thêm video để bắt đầu dựng</span></div>}</div><div className="transport"><button onClick={()=>seek(0)}>⏮</button><button onClick={()=>preview.current?.paused?void preview.current.play():preview.current?.pause()}>▶ / ❚❚</button><strong>{clock(playhead)} / {clock(duration)}</strong><input aria-label="Playhead" type="range" min="0" max={Math.max(duration,.01)} step=".01" value={Math.min(playhead,duration)} onChange={event=>seek(Number(event.target.value))}/><label>Zoom <input type="range" min=".5" max="2.5" step=".25" value={zoom} onChange={event=>setZoom(Number(event.target.value))}/></label></div></main>
      <aside className="editor-inspector"><h3>Thuộc tính</h3>{!selection&&<p>Chọn một clip trên timeline để chỉnh sửa.</p>}
        {selectedVideo&&<div className="inspector-fields"><strong>{basename(selectedVideo.path)}</strong><label>Trim đầu (giây)<input type="number" min="0" max={Math.max(0,selectedVideo.trimEnd-.01)} step=".05" value={selectedVideo.trimStart} onChange={event=>updateVideo({trimStart:Math.min(Number(event.target.value),selectedVideo.trimEnd-.01)})}/></label><label>Trim cuối (giây)<input type="number" min={selectedVideo.trimStart+.01} max={selectedVideo.duration} step=".05" value={selectedVideo.trimEnd} onChange={event=>updateVideo({trimEnd:Math.max(Number(event.target.value),selectedVideo.trimStart+.01)})}/></label><label>Tốc độ<select value={selectedVideo.speed} onChange={event=>updateVideo({speed:Number(event.target.value)})}>{[.25,.5,.75,1,1.25,1.5,2,3,4].map(value=><option value={value} key={value}>{value}×</option>)}</select></label><label>Thời lượng sau dựng<input value={`${clipDuration(selectedVideo).toFixed(2)} giây`} readOnly/></label><label>Độ phân giải<input value={`${selectedVideo.width} × ${selectedVideo.height}`} readOnly/></label></div>}
        {selection?.kind==="audio"&&audio&&<div className="inspector-fields"><strong>{basename(audio.path)}</strong><label>Âm lượng<input disabled={tracks.audioLocked||tracks.audioMuted} type="range" min="0" max="2" step=".05" value={audioVolume} onChange={event=>{checkpoint();setAudioVolume(Number(event.target.value));}}/><output>{tracks.audioMuted?"Tắt tiếng":`${Math.round(audioVolume*100)}%`}</output></label><label>Thời lượng<input value={`${audio.duration.toFixed(2)} giây`} readOnly/></label></div>}
        {selectedLogo&&<div className="inspector-fields"><strong>{basename(selectedLogo.path)}</strong><label>Bắt đầu (giây)<input type="number" min="0" max={Math.max(0,duration-.01)} step=".05" value={selectedLogo.timelineStart} onChange={event=>updateLogo({timelineStart:Number(event.target.value)})}/></label><label>Kết thúc (giây)<input type="number" min={selectedLogo.timelineStart+.01} max={Math.max(duration,.01)} step=".05" value={selectedLogo.timelineEnd??duration} onChange={event=>updateLogo({timelineEnd:Number(event.target.value)})}/></label><label>Chuyển động<select value={selectedLogo.mode} onChange={event=>updateLogo({mode:event.target.value as Logo["mode"]})}><option value="static">Cố định</option><option value="bounce">Bật nẩy</option><option value="horizontal">Trượt ngang</option><option value="vertical">Trượt dọc</option></select></label><label>Vị trí<select value={selectedLogo.position} onChange={event=>updateLogo({position:event.target.value as Logo["position"]})}>{positions.map(value=><option key={value}>{value}</option>)}</select></label><label>Kích thước<input type="range" min="24" max="640" value={selectedLogo.width} onChange={event=>updateLogo({width:Number(event.target.value)})}/><output>{selectedLogo.width}px</output></label><label>Độ mờ<input type="range" min=".05" max="1" step=".05" value={selectedLogo.opacity} onChange={event=>updateLogo({opacity:Number(event.target.value)})}/><output>{Math.round(selectedLogo.opacity*100)}%</output></label><label>Màu sắc<input type="range" min="-180" max="180" value={selectedLogo.hue} onChange={event=>updateLogo({hue:Number(event.target.value)})}/></label><label>Nền<input type="color" value={selectedLogo.backgroundColor} onChange={event=>updateLogo({backgroundColor:event.target.value})}/></label>{selectedLogo.mode!=="static"&&<><label>Tốc độ ngang<input type="number" min="1" max="600" value={selectedLogo.speedX} onChange={event=>updateLogo({speedX:Number(event.target.value)})}/></label><label>Tốc độ dọc<input type="number" min="1" max="600" value={selectedLogo.speedY} onChange={event=>updateLogo({speedY:Number(event.target.value)})}/></label></>}</div>}
        {selection&&<button className="danger inspector-remove" disabled={(selection.kind==="video"&&tracks.videoLocked)||(selection.kind==="audio"&&tracks.audioLocked)||(selection.kind==="logo"&&tracks.overlayLocked)} onClick={removeSelection}>Xóa khỏi timeline</button>}
      </aside>
    </div>
    <section className="timeline-panel"><header><div><button onClick={()=>void addVideos()}>＋ Thêm media</button><button disabled={!selection} onClick={removeSelection}>⌫ Xóa</button></div><span>Kéo clip video để đổi thứ tự · chọn clip để trim, đổi tốc độ hoặc đặt thời gian overlay</span></header><div className="timeline-scroll"><div className="timeline-content" style={{width:timelineWidth}} onClick={event=>{const rect=event.currentTarget.getBoundingClientRect(),laneWidth=Math.max(1,rect.width-92),laneX=event.clientX-rect.left-92;seek(Math.max(0,Math.min(duration,laneX/laneWidth*duration)));}}><div className="timeline-ruler">{Array.from({length:11},(_,index)=><span key={index} style={{left:`${index*10}%`}}>{clock(duration*index/10)}</span>)}</div><div className="playhead" style={{left:`${92+(duration?playhead/duration*(timelineWidth-92):0)}px`,marginLeft:0}}/>
      <div className={`timeline-track${tracks.videoLocked?" locked":""}`}><b><span>VIDEO</span><button title="Khóa track video" onClick={event=>{event.stopPropagation();checkpoint();setTracks(value=>({...value,videoLocked:!value.videoLocked}));}}>{tracks.videoLocked?"🔒":"🔓"}</button></b><div className="track-lane video-lane">{videos.map(item=><button draggable={!tracks.videoLocked} onDragStart={()=>{if(!tracks.videoLocked)setDragged(item.id);}} onDragOver={event=>event.preventDefault()} onDrop={()=>dropVideo(item.id)} onClick={event=>{event.stopPropagation();setSelection({kind:"video",id:item.id});}} className={`timeline-clip video-clip${selection?.id===item.id?" selected":""}`} style={{width:`${Math.max(90,clipDuration(item)/Math.max(duration,.01)*(timelineWidth-92))}px`}} key={item.id}><span className="trim-handle trim-start" onPointerDown={event=>startTrim(event,item,"start")} title="Kéo để trim đầu"/><span className="clip-title">{basename(item.path)}</span><small>{clock(clipDuration(item))} · {item.speed}×</small><span className="trim-handle trim-end" onPointerDown={event=>startTrim(event,item,"end")} title="Kéo để trim cuối"/></button>)}</div></div>
      <div className={`timeline-track${tracks.audioLocked?" locked":""}${tracks.audioMuted?" muted":""}`}><b><span>AUDIO</span><span className="track-actions"><button title="Khóa track audio" onClick={event=>{event.stopPropagation();checkpoint();setTracks(value=>({...value,audioLocked:!value.audioLocked}));}}>{tracks.audioLocked?"🔒":"🔓"}</button><button title="Bật/tắt âm thanh" onClick={event=>{event.stopPropagation();checkpoint();setTracks(value=>({...value,audioMuted:!value.audioMuted}));}}>{tracks.audioMuted?"🔇":"🔊"}</button></span></b><div className="track-lane">{audio&&<button onClick={event=>{event.stopPropagation();setSelection({kind:"audio",id:audio.id});}} className={`timeline-clip audio-clip${selection?.id===audio.id?" selected":""}`} style={{width:`${Math.min(100,audio.duration/Math.max(duration,.1)*100)}%`,backgroundImage:audio.waveformPath?`linear-gradient(#4f2f7077,#4f2f7077),url(${fileUrl(audio.waveformPath)})`:undefined}}>♫ {basename(audio.path)} · {tracks.audioMuted?"Muted":`${Math.round(audioVolume*100)}%`}</button>}</div></div>
      <div className={`timeline-track${tracks.overlayLocked?" locked":""}`}><b><span>OVERLAY</span><button title="Khóa track overlay" onClick={event=>{event.stopPropagation();checkpoint();setTracks(value=>({...value,overlayLocked:!value.overlayLocked}));}}>{tracks.overlayLocked?"🔒":"🔓"}</button></b><div className="track-lane logo-lane">{logos.map(item=>{const start=Math.min(item.timelineStart,duration),end=Math.min(item.timelineEnd??duration,duration);return <button onClick={event=>{event.stopPropagation();setSelection({kind:"logo",id:item.id});}} className={`timeline-clip logo-clip${selection?.id===item.id?" selected":""}`} style={{left:`${duration?start/duration*100:0}%`,width:`${duration?Math.max(.5,(end-start)/duration*100):100}%`}} key={item.id}>◇ {basename(item.path)}</button>;})}</div></div>
    </div></div></section>
    {error&&<p className="inline-error">{error}</p>}{message&&<p className="success-note">{message}</p>}
  </section>;
}
