import {useState} from "react";
import {api} from "./api";
import {EvidenceProbe} from "./evidence-probe";
import {t} from "./i18n";
import {useAppStore} from "./store";
import {forgottenUiStatePatch} from "./ui-state";
const values=(items:number[])=>items.map(value=><option key={value}>{value}</option>);
export function SettingsPanel({tools,debugFileName,setDebugFileName,updatesConfigured}:{tools:Array<{name:string;available:boolean;version:string|null}>;debugFileName:string;setDebugFileName:(value:string)=>void;updatesConfigured:boolean}){
  const {settings,saveSettings}=useAppStore();const [updateMessage,setUpdateMessage]=useState("");
  async function pickFolder(){const dir=await api.settings.pickDir();if(dir)await saveSettings({downloadDir:dir});}
  async function toggleRemember(checked:boolean){await saveSettings({rememberUiState:checked,...(!checked?forgottenUiStatePatch():{})});}
  async function checkUpdates(){setUpdateMessage(t("update_checking"));try{const result=await api.app.checkUpdates();setUpdateMessage(result.state==="available"?`${t("update_available")}${result.version?`: ${result.version}`:""}`:result.state==="not-available"?t("update_not_available"):result.state==="not-configured"?t("update_not_configured"):t("update_error"));}catch{setUpdateMessage(t("update_error"));}}
  return <section className="settings-page"><header className="page-heading"><h2>{t("tab_settings")}</h2><p>{t("settings_hint")}</p></header><div className="settings-grid">
    <section className="settings-card"><h3>{t("settings_download")}</h3><label>{t("download_folder")}<div className="field-with-button"><input value={settings?.downloadDir??""} onChange={event=>void saveSettings({downloadDir:event.target.value})}/><button onClick={()=>void pickFolder()}>{t("browse")}</button></div></label><label>{t("concurrent")}<select value={settings?.concurrency??2} onChange={event=>void saveSettings({concurrency:Number(event.target.value)})}>{values([1,2,3,4,5,6,7,8])}</select></label><label>{t("per_domain_concurrent")}<select value={settings?.perDomainConcurrency??1} onChange={event=>void saveSettings({perDomainConcurrency:Number(event.target.value)})}>{values([1,2,3,4])}</select></label><label>{t("cookies")}<select value={settings?.cookiesFromBrowser??"none"} onChange={event=>void saveSettings({cookiesFromBrowser:event.target.value as "none"|"edge"|"chrome"|"firefox"})}><option value="none">{t("none")}</option><option value="edge">Edge</option><option value="chrome">Chrome</option><option value="firefox">Firefox</option></select></label></section>
    <section className="settings-card"><h3>{t("settings_storage")}</h3><label>{t("history_retention")}<select value={settings?.historyRetentionDays??90} onChange={event=>void saveSettings({historyRetentionDays:Number(event.target.value)})}>{values([7,30,90,365,1095])}</select></label><label>{t("log_retention")}<select value={settings?.logRetentionDays??30} onChange={event=>void saveSettings({logRetentionDays:Number(event.target.value)})}>{values([7,14,30,90,365])}</select></label><label>{t("backup_retention")}<select value={settings?.backupRetentionCount??3} onChange={event=>void saveSettings({backupRetentionCount:Number(event.target.value)})}>{values([1,2,3,5,10])}</select></label><label className="checkbox-row"><input type="checkbox" checked={settings?.rememberUiState??true} onChange={event=>void toggleRemember(event.target.checked)}/>{t("remember_ui_state")}</label></section>
    <section className="settings-card"><h3>{t("settings_tools")}</h3><div className="tools">{tools.map(tool=><span key={tool.name} className={tool.available?"ok":"missing"}>{tool.name} {tool.available?tool.version:t("missing")}</span>)}</div>{updatesConfigured&&<button onClick={()=>void checkUpdates()}>{t("check_updates")}</button>}{updateMessage&&<span className="update-note">{updateMessage}</span>}</section>
    <section className="settings-card"><h3>{t("settings_diagnostics")}</h3><div className="diagnostics-export"><input value={debugFileName} onChange={event=>setDebugFileName(event.target.value)} placeholder={t("debug_name_placeholder")} maxLength={120}/><button onClick={()=>void api.app.exportDiagnostics(debugFileName)}>{t("export_diagnostics")}</button></div></section>
    <section className="settings-card privacy-card"><h3>{t("settings_privacy")}</h3><label className="checkbox-row"><input type="checkbox" checked={settings?.allowThirdPartyXFallback??false} onChange={event=>void saveSettings({allowThirdPartyXFallback:event.target.checked})}/>{t("allow_x_fallback")}</label><p>{t("x_fallback_disclosure")}</p></section>
  </div><EvidenceProbe/></section>;
}
